apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shuffle-api
  description: Shuffle API
  labels:
    goVersion: go1.15.3
    category: music
  links:
    - url: https://github.com/zabybabaye/firstone
      title: GitHub Repo
  tags:
    - go
    - nfl
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: audio-playback
